name: Ruby Sinatra CI

on:
#  push:
#    branches:
#      - feat-delegacion
   workflow_dispatch:
       branches:
          - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true

    - name: Install Bundler 2.4.22
      run: gem install bundler -v 2.4.22

    - name: Create Gemfile
      run: |
        echo "source 'https://rubygems.org'" > Gemfile
        echo "ruby '3.0.0'" >> Gemfile
        echo "gem 'sinatra'" >> Gemfile
        echo "gem 'rspec'" >> Gemfile
        echo "gem 'rake'" >> Gemfile
        echo "gem 'rackup'" >> Gemfile
      

    - name: Install dependencies
      run: |
        cat Gemfile
        bundle install

    - name: Run tests
      run: |
        bundle exec rspec 
      
    - name: Start Server
      run: |
        ruby ./temas/delegacion/ruby/Orquesta.rb 
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    - name: Install dependencies
      run: gem install test-unit

    - name: Run Ruby tests
      run: ruby ./temas/delegacion/ruby/testOrquesta.rb
